// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMeetingRoom.API.Data;

#nullable disable

namespace SmartMeetingRoom.API.Migrations
{
    [DbContext(typeof(SmartMeetingRoomDBContext))]
    [Migration("20250811120513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.ActionItem", b =>
                {
                    b.Property<int>("ActionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionItemId"));

                    b.Property<string>("ActionItemDescription")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("ActionItemDueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ActionItemStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("FkMeetingMinutesId")
                        .HasColumnType("int")
                        .HasColumnName("FK_MeetingMinutesId");

                    b.Property<int>("FkUserId")
                        .HasColumnType("int")
                        .HasColumnName("FK_UserId");

                    b.HasKey("ActionItemId")
                        .HasName("PK__ActionIt__56285AB24BCFCCD3");

                    b.HasIndex("FkMeetingMinutesId");

                    b.HasIndex("FkUserId");

                    b.ToTable("ActionItem", (string)null);
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RoleName");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RoleDescription")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("No description provided.");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FkRoleId")
                        .HasColumnType("int")
                        .HasColumnName("FK_RoleId");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FkRoleId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Attendee", b =>
                {
                    b.Property<int>("AttendeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendeeId"));

                    b.Property<string>("AttendeeStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Invited");

                    b.Property<int>("FkMeetingId")
                        .HasColumnType("int")
                        .HasColumnName("FK_MeetingId");

                    b.Property<int>("FkUserId")
                        .HasColumnType("int")
                        .HasColumnName("FK_UserId");

                    b.HasKey("AttendeeId")
                        .HasName("PK__Attendee__1844010811F545B0");

                    b.HasIndex("FkMeetingId");

                    b.HasIndex(new[] { "FkUserId", "FkMeetingId" }, "UQ_UserMeeting")
                        .IsUnique();

                    b.ToTable("Attendee", (string)null);
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Feature", b =>
                {
                    b.Property<byte>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("FeatureId"));

                    b.Property<string>("FeatureDescription")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("No description provided");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FeatureId")
                        .HasName("PK__Feature__82230BC9BF3A9108");

                    b.HasIndex(new[] { "FeatureName" }, "UQ__Feature__55ABBB7113EB1BDE")
                        .IsUnique();

                    b.ToTable("Feature", (string)null);
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingId"));

                    b.Property<int>("FkRoomId")
                        .HasColumnType("int")
                        .HasColumnName("FK_RoomId");

                    b.Property<int>("FkUserId")
                        .HasColumnType("int")
                        .HasColumnName("FK_UserId");

                    b.Property<string>("MeetingAgenda")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("MeetingEndTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("MeetingStartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MeetingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Scheduled");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MeetingId")
                        .HasName("PK__Meeting__E9F9E94C34FD7662");

                    b.HasIndex("FkRoomId");

                    b.HasIndex("FkUserId");

                    b.ToTable("Meeting", (string)null);
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.MeetingMinute", b =>
                {
                    b.Property<int>("MeetingMinutesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingMinutesId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FkMeetingId")
                        .HasColumnType("int")
                        .HasColumnName("FK_MeetingId");

                    b.Property<int>("FkUserId")
                        .HasColumnType("int")
                        .HasColumnName("FK_UserId");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<string>("MeetingSummary")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("MeetingMinutesId")
                        .HasName("PK__MeetingM__58772D4754871672");

                    b.HasIndex("FkMeetingId");

                    b.HasIndex("FkUserId");

                    b.ToTable("MeetingMinutes");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte>("RoomCapacity")
                        .HasColumnType("tinyint");

                    b.Property<string>("RoomLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoomId")
                        .HasName("PK__Room__328639390ACAD311");

                    b.HasIndex(new[] { "RoomName" }, "UQ__Room__6B500B55D76ABCBD")
                        .IsUnique();

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.RoomFeature", b =>
                {
                    b.Property<int>("RoomFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomFeatureId"));

                    b.Property<byte>("FkFeatureId")
                        .HasColumnType("tinyint")
                        .HasColumnName("FK_FeatureId");

                    b.Property<int>("FkRoomId")
                        .HasColumnType("int")
                        .HasColumnName("FK_RoomId");

                    b.HasKey("RoomFeatureId")
                        .HasName("PK__RoomFeat__E554235C70F7C736");

                    b.HasIndex("FkFeatureId");

                    b.HasIndex("FkRoomId");

                    b.ToTable("RoomFeature", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.ActionItem", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.MeetingMinute", "FkMeetingMinutes")
                        .WithMany("ActionItems")
                        .HasForeignKey("FkMeetingMinutesId")
                        .IsRequired()
                        .HasConstraintName("FK__ActionIte__FK_Me__7E37BEF6");

                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", "FkUser")
                        .WithMany("ActionItems")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK__ActionIte__FK_Us__7F2BE32F");

                    b.Navigation("FkMeetingMinutes");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.ApplicationUser", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationRole", "FkRole")
                        .WithMany("Users")
                        .HasForeignKey("FkRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("FkRole");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Attendee", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.Meeting", "FkMeeting")
                        .WithMany("Attendees")
                        .HasForeignKey("FkMeetingId")
                        .IsRequired()
                        .HasConstraintName("FK__Attendee__FK_Mee__73BA3083");

                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", "FkUser")
                        .WithMany("Attendees")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Attendee__FK_Use__72C60C4A");

                    b.Navigation("FkMeeting");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Meeting", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.Room", "FkRoom")
                        .WithMany("Meetings")
                        .HasForeignKey("FkRoomId")
                        .IsRequired()
                        .HasConstraintName("FK__Meeting__FK_Room__6C190EBB");

                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", "FkUser")
                        .WithMany("Meetings")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Meeting__FK_User__6B24EA82");

                    b.Navigation("FkRoom");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.MeetingMinute", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.Meeting", "FkMeeting")
                        .WithMany("MeetingMinutes")
                        .HasForeignKey("FkMeetingId")
                        .IsRequired()
                        .HasConstraintName("FK__MeetingMi__FK_Me__787EE5A0");

                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", "FkUser")
                        .WithMany("MeetingMinutes")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK__MeetingMi__FK_Us__797309D9");

                    b.Navigation("FkMeeting");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.RefreshToken", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.RoomFeature", b =>
                {
                    b.HasOne("SmartMeetingRoom.API.Models.Feature", "FkFeature")
                        .WithMany("RoomFeatures")
                        .HasForeignKey("FkFeatureId")
                        .IsRequired()
                        .HasConstraintName("FK__RoomFeatu__FK_Fe__6754599E");

                    b.HasOne("SmartMeetingRoom.API.Models.Room", "FkRoom")
                        .WithMany("RoomFeatures")
                        .HasForeignKey("FkRoomId")
                        .IsRequired()
                        .HasConstraintName("FK__RoomFeatu__FK_Ro__66603565");

                    b.Navigation("FkFeature");

                    b.Navigation("FkRoom");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.ApplicationRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.ApplicationUser", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Attendees");

                    b.Navigation("MeetingMinutes");

                    b.Navigation("Meetings");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Feature", b =>
                {
                    b.Navigation("RoomFeatures");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Meeting", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("MeetingMinutes");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.MeetingMinute", b =>
                {
                    b.Navigation("ActionItems");
                });

            modelBuilder.Entity("SmartMeetingRoom.API.Models.Room", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("RoomFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
